### ISSUE TITLE
A little confusion..

### ISSUE THREAD

**Issue by evi-Genius** [jakc4103/DFQ#5]
Hi, I want to know how to handle this situation exactly, I have limited ability to read the code..
 c. many to many. ex: BatchNorm1->ReLU->
 ------------------------------------------------------QuantAdd->
------------------------------ BatchNorm2->ReLU->-----;---------QuantAdd -> input
---------------------------------------------- BatchNorm3->ReLU->
Does it mean the range of input is [0,beta+n×gamma]?
And beta=(BatchNorm1.beta+BatchNorm2.beta+BatchNorm3.beta)/3
       gamma=(BatchNorm1.gamma+BatchNorm2.gamma+BatchNorm3.gamma)/3

**Comment by jakc4103** [comment]
In the previous version. I handle the residual connection in first version as:
value_min=(value_min_BatchNorm1+value_min_BatchNorm2+value_min_BatchNorm3)/3
value_max=(value_max_BatchNorm1+value_max_BatchNorm2+value_max_BatchNorm3)/3

and in current version as:
value_min=[(value_min_BatchNorm1+value_min_BatchNorm2)/2+value_min_BatchNorm3]/2
value_max=[(value_max_BatchNorm1+value_max_BatchNorm2)/2+value_max_BatchNorm3]/2

in my local version, i've also tried:
mean=[(BatchNorm1.mean+BatchNorm2.mean)/2+BatchNorm3.mean]/2
var=[(BatchNorm1.var+BatchNorm2.var)/2+BatchNorm3.var]/2
value_min = max(0, mean-n×std)
value_max = mean+n×std

These 3 methods did not make big difference though. Since the original paper did not mention how they handle this problem, it kind of difficult to reproduce the performance from the paper.

**Comment by evi-Genius** [comment]
> In the previous version. I handle the residual connection in first version as:
> value_min=(value_min_BatchNorm1+value_min_BatchNorm2+value_min_BatchNorm3)/3
> value_max=(value_max_BatchNorm1+value_max_BatchNorm2+value_max_BatchNorm3)/3
> 
> and in current version as:
> value_min=[(value_min_BatchNorm1+value_min_BatchNorm2)/2+value_min_BatchNorm3]/2
> value_max=[(value_max_BatchNorm1+value_max_BatchNorm2)/2+value_max_BatchNorm3]/2
> 
> in my local version, i've also tried:
> mean=[(BatchNorm1.mean+BatchNorm2.mean)/2+BatchNorm3.mean]/2
> var=[(BatchNorm1.var+BatchNorm2.var)/2+BatchNorm3.var]/2
> value_min = max(0, mean-n×std)
> value_max = mean+n×std
> 
> These 3 methods did not make big difference though. Since the original paper did not mention how they handle this problem, it kind of difficult to reproduce the performance from the paper.

I get. Thanks for your kind reply!
