### ISSUE TITLE
Could you explain the funciton "set_quant_minmax"

### ISSUE THREAD

**Issue by z13974509906** [jakc4103/DFQ#8]
We found it very useful to cal min and max of input data by set_quant_minmax, instead of calibrating.
But the logic is not very clearly, can you explain it in detail?
Appreciate for your help~

**Comment by z13974509906** [comment]
Or is there any literature I can refer to?

**Comment by jakc4103** [comment]
No, there is no literature, even the original paper did not quite mentions this part, neither.

According to the original paper, it's easy to calculate min/max in single sequential path networks; the tricky part is the branches like residual addition and concatenate op. I have tested some strategies and found current implementation worked and much more reasonable.

1. addition case, I sum the mean and variance of all input statistics (from bn), then cal min/max in final step; 
2. concatenate case, I use the minimum and maximum of min/max all input statistics (from bn);
3. otherwise, I use mean value of min/max of all input statistics (from bn);

When calculating min/max with the 3 rules above, I followed the orders in branching.
ex: out1 and out2 should be summed first, then sum to out3.

**Comment by z13974509906** [comment]
My understanding: The output of the BN layer has a mean of gamma and a variance of beta. Assuming a Gaussian distribution and set N = 6, so we can assume the min is **gamma - N * beta**, max is **gamm + N * bta**, am I right?

**Comment by jakc4103** [comment]
> My understanding: The output of the BN layer has a mean of gamma and a variance of beta. Assuming a Gaussian distribution and set N = 6, so we can assume the min is **gamma - N * beta**, max is **gamm + N * bta**, am I right?

Yes, this is the proposed estimation method from DFQ paper.
I guess they assume all activations follow Gaussian distribution and is independent

**Comment by z13974509906** [comment]
> No, there is no literature, even the original paper did not quite mentions this part, neither.
> 
> According to the original paper, it's easy to calculate min/max in single sequential path networks; the tricky part is the branches like residual addition and concatenate op. I have tested some strategies and found current implementation worked and much more reasonable.
> 
> 1. addition case, I sum the mean and variance of all input statistics (from bn), then cal min/max in final step;
> 2. concatenate case, I use the minimum and maximum of min/max all input statistics (from bn);
> 3. otherwise, I use mean value of min/max of all input statistics (from bn);
> 
> When calculating min/max with the 3 rules above, I followed the orders in branching.
> ex: out1 and out2 should be summed first, then sum to out3.
Thanks for your reply!!!
 I think the situation with branches is more complicated, I will read your code in detail.
